os: Visual Studio 2019

environment:
  HOME: "%HOMEDRIVE%%HOMEPATH%"
  PYTHON: C:\Python27
  SCONS_CACHE: "%HOME%\\scons_cache"
  matrix:
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      LM_PLATFORM: windows
      TOOLS: yes
      TARGET: release
      ARCH: amd64

cache:
  - "%SCONS_CACHE%"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons
  - if defined VS call "%VS%" %ARCH% # if defined - so we can also use mingw
  - git submodule update --init --recursive

before_build:
  - mkdir build

build_script:
  - scons platform=%LM_PLATFORM% bits=64 target=%TARGET%

artifacts:
  - path: addons/qodot/bin/win64/*.dll

deploy:
  - provider: GitHub
    auth_token:
      secure: YCKQJa/VO6nHDC8/iCOtJbqQ0nri+/S6zhEHnYzUAj43tmZwxnWQ6NjDB78FZY0v
    repository: Shfty/libqodot
    artifact: build/*.dll
    draft: true
    force_update: true
    tag: latest
